name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux-x64', 'linux-arm', 'linux-arm64', 'windows', 'macOS-x64']
        include:
          - kind: linux-x64
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-arm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: linux-arm
            os: ubuntu-latest
            target: linux-arm
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS-x64
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet publish --framework net5.0 --runtime "${{ matrix.target }}" -c Release
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: PhotoCopy-$tag-${{ matrix.target }}
          path: bin\Release\net5.0\{{ matrix.target }}\publish

